backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# Uncomment below to enable drafts
# publish_mode: editorial_workflow

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  # Our blog posts
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Summary", name: "summary", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: ["post"] }
      - { label: "Body", name: "body", widget: "markdown" }
  # Our homepage sections
  - name: "home_section" # Used in routes, e.g., /admin/collections/blog
    label: "Home Section" # Used in the UI
    folder: "sections" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Tags", name: "tags", widget: "hidden", default: "home_sections" }
      - { label: "ID", name: "id", widget: "string", hint: "Must be 1 word, all lowercase." }
      - { label: "Background Color", name: "bgcolor", widget: "string" }
      - { label: "Image", name: "image", widget: "image", allow_mutliple: false }
      - { label: "Body", name: "body", widget: "markdown" }
  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Subtitle", name: "subtitle", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", hint: "Appears just under the subtitle", required: false }
      - label: "Page Sections"
        name: "page_sections"
        widget: "list"
        collapsed: false
        types:
          - label: 'Content'
            name: 'content'
            typeKey: id
            widget: object
            fields:
              - { label: "Title", name: "title", widget: "string", required: false, hint: "Leave blank if continuation of previous section" }
              - { label: "ID", name: "id", widget: "string", hint: "No spaces, all lowercase pleeeease" }
              - { label: "Background", name: "bgcolor", widget: "string", hint: "Use hex code e.g. /#FCFCFC or other more complex CSS gradients" }
              - { label: "Light Text", name: "lighttext", widget: boolean, required: false, hint: "Switch on if using a dark background color"}
              - { label: "Pre-Body", name: "prebody", widget: "markdown", hint: "Appears before the columns", required: false  }
              - label: Columns
                name: cols
                widget: list
                field: { label: "Column Content", name: colbody, widget: markdown, required: true }
              - { label: "Post-Body", name: "postbody", widget: "markdown", hint: "Appears after the columns", required: false  }
          - label: Wide Image
            name: wide_image
            widget: object
            field: { label: Image, name: image, widget: image, allow_mutliple: false }
